# Generated by Django 4.0.3 on 2022-04-25 00:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('newsletters', models.BooleanField(default=True)),
                ('subscriptions', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rkey', models.CharField(default='none', max_length=255)),
                ('type', models.CharField(choices=[('USER', 'User'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='USER', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('author', models.CharField(max_length=255)),
                ('ISBN', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('numSold', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to='images')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('newsletters', models.BooleanField(default=True)),
                ('subscriptions', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rkey', models.CharField(default='none', max_length=255)),
                ('type', models.CharField(choices=[('USER', 'User'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='USER', max_length=6)),
                ('organizationName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailTitle', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('scheduledTime', models.DateField()),
                ('attachment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('code', models.CharField(max_length=24, unique=True)),
                ('pctdiscount', models.IntegerField(blank=True, max_length=4, null=True)),
                ('amountdiscount', models.IntegerField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateField(default=datetime.date(2022, 4, 29))),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('newsletters', models.BooleanField(default=True)),
                ('subscriptions', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rkey', models.CharField(default='none', max_length=255)),
                ('type', models.CharField(choices=[('USER', 'User'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='USER', max_length=6)),
                ('birthDate', models.DateField()),
                ('phone', models.IntegerField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=255)),
                ('vkey', models.CharField(default='none', max_length=255)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('newsletters', models.BooleanField(default=True)),
                ('subscriptions', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rkey', models.CharField(default='none', max_length=255)),
                ('type', models.CharField(choices=[('USER', 'User'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='USER', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.IntegerField()),
                ('address', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2022, 4, 24))),
                ('purchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservedBookID', to='website.book')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationID', to='website.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservingUserID', to='website.user'),
        ),
        migrations.CreateModel(
            name='CartBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartBook', to='website.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartUser', to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.IntegerField()),
                ('saleDate', models.DateField(default=datetime.date(2022, 4, 24))),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookID', to='website.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_creator', to='website.vendor'),
        ),
        migrations.CreateModel(
            name='ClientBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.book',),
        ),
        migrations.CreateModel(
            name='VendorBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.book',),
        ),
    ]
