# Generated by Django 4.0.3 on 2022-04-22 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.book',),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='saleDate',
            field=models.DateField(default=datetime.date(2022, 4, 22)),
        ),
    ]
