# Generated by Django 4.0.4 on 2022-04-22 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='rkey',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='admin',
            name='type',
            field=models.CharField(default='USER', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='rkey',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(default='USER', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='rkey',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='USER', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rkey',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='type',
            field=models.CharField(default='USER', max_length=255),
        ),
        migrations.AlterField(
            model_name='booksale',
            name='saleDate',
            field=models.DateField(default=datetime.date(2022, 4, 22)),
        ),
    ]
