# Generated by Django 4.0.4 on 2022-04-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_admin_rkey_admin_type_client_rkey_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='cart',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='client',
            name='cart',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cart',
            field=models.TextField(default='empty'),
        ),
    ]
