# Generated by Django 4.0.4 on 2022-04-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_admin_cart_client_cart_user_cart_vendor_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='cart',
        ),
        migrations.AlterField(
            model_name='admin',
            name='type',
            field=models.CharField(choices=[('USER', 'User'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='USER', max_length=6),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('USER', 'User'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='USER', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('USER', 'User'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='USER', max_length=6),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='type',
            field=models.CharField(choices=[('USER', 'User'), ('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='USER', max_length=6),
        ),
    ]
